name: singleton-sidekiq-jobs-local-development

services:
  db:
    image: postgres:16.3-bullseye
    shm_size: 128mb
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      PGPASSWORD: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.6
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis-db:/data
